[build]
  # 빌드 명령어 - Netlify 환경변수로 env.js 덮어쓰기
  command = '''
    echo "window.ENV = {
      SUPABASE_URL: '$SUPABASE_URL',
      SUPABASE_ANON_KEY: '$SUPABASE_ANON_KEY', 
      ADMIN_EMAIL: '$ADMIN_EMAIL',
      NODE_ENV: 'production'
    };" > js/env.js
  '''
  
  # 배포할 폴더
  publish = "."
